@echo off
echo Starting Digital Studio App...

:: Start Backend
echo Starting Backend (Spring Boot)...
start "Digital Studio Backend" cmd /k "cd backend && mvn spring-boot:run"

:: Start Frontend
echo Starting Frontend (Vite)...
start "Digital Studio Frontend" cmd /k "cd frontend && npm run dev"

echo App is starting...
