package com.digitalstudio.app.service;

import com.digitalstudio.app.model.MoneyTransfer;
import com.digitalstudio.app.model.Customer;
import com.digitalstudio.app.repository.MoneyTransferRepository;
import com.digitalstudio.app.repository.CustomerRepository;
import com.digitalstudio.app.repository.UploadRepository;
import com.digitalstudio.app.model.FinancialTransaction;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;
import jakarta.persistence.criteria.Predicate;

import java.time.LocalDate;
import java.util.*;
import java.util.UUID;

@Service
public class MoneyTransferService {

    @Autowired
    private MoneyTransferRepository moneyTransferRepository;

    @Autowired
    private UploadRepository uploadRepository;

    @Autowired
    private CustomerRepository customerRepository;

    @Autowired
    private CustomerService customerService;

    @Autowired
    private FinancialService financialService;

    @Autowired
    private com.fasterxml.jackson.databind.ObjectMapper objectMapper;

    public Page<MoneyTransfer> getAllTransfers(LocalDate startDate, LocalDate endDate,
            String search, List<String> types, int page, int size) {
        Specification<MoneyTransfer> spec = (root, query, cb) -> {
            List<Predicate> predicates = new ArrayList<>();

            if (startDate != null) {
                predicates.add(cb.greaterThanOrEqualTo(root.get("createdAt"), startDate.atStartOfDay()));
            }
            if (endDate != null) {
                predicates.add(cb.lessThanOrEqualTo(root.get("createdAt"), endDate.atTime(23, 59, 59)));
            }

            if (types != null && !types.isEmpty()) {
                predicates.add(root.get("transferType").in(types));
            }

            if (search != null && !search.isEmpty()) {
                String likePattern = "%" + search.toLowerCase() + "%";
                Predicate customerName = cb.like(cb.lower(root.get("customer").get("name")), likePattern);
                Predicate recipientName = cb.like(cb.lower(root.get("recipientName")), likePattern);
                Predicate upiId = cb.like(cb.lower(root.get("upiId")), likePattern);
                Predicate accountNumber = cb.like(cb.lower(root.get("accountNumber")), likePattern);
                Predicate status = cb.like(cb.lower(root.get("status")), likePattern);
                predicates.add(cb.or(customerName, recipientName, upiId, accountNumber, status));
            }

            return cb.and(predicates.toArray(new Predicate[0]));
        };

        Page<MoneyTransfer> pageData = moneyTransferRepository.findAll(spec,
                PageRequest.of(page, size, Sort.by(Sort.Direction.DESC, "createdAt")));

        for (MoneyTransfer mt : pageData.getContent()) {
            if (mt.getUploadId() != null) {
                String rawId = mt.getUploadId();
                if (rawId.contains(".")) {
                    rawId = rawId.substring(0, rawId.lastIndexOf('.'));
                }
                uploadRepository.findById(rawId).ifPresent(upload -> {
                    mt.setIsFileAvailable(upload.getIsAvailable());
                });
            }
        }

        return pageData;
    }

    public MoneyTransfer createTransfer(MoneyTransfer transfer) {
        // IDs are now auto-generated by JPA UUID strategy.

        if (transfer.getCustomer() != null) {
            Customer payloadCustomer = transfer.getCustomer();
            if (payloadCustomer.getId() == null) {
                if (payloadCustomer.getMobile() != null && !payloadCustomer.getMobile().isEmpty()) {
                    Customer existing = customerRepository.findByMobile(payloadCustomer.getMobile()).orElse(null);
                    if (existing != null) {
                        transfer.setCustomer(existing);
                    } else {
                        Customer newCust = new Customer();
                        newCust.setMobile(payloadCustomer.getMobile());
                        newCust.setName(payloadCustomer.getName());
                        newCust.setId(customerService.generateNewCustomerId());
                        transfer.setCustomer(customerRepository.save(newCust));
                    }
                }
            }
        }

        if (transfer.getStatus() == null) {
            transfer.setStatus("Pending");
        }

        // Initialize Status History
        try {
            java.util.List<java.util.Map<String, Object>> history = new java.util.ArrayList<>();
            java.util.Map<String, Object> entry = new java.util.HashMap<>();
            entry.put("status", transfer.getStatus());
            entry.put("timestamp", java.time.LocalDateTime.now().toString());
            history.add(entry);
            transfer.setStatusHistoryJson(objectMapper.writeValueAsString(history));
        } catch (Exception e) {
            System.err.println("Error initializing status history: " + e.getMessage());
        }

        MoneyTransfer saved = moneyTransferRepository.save(transfer);

        // Record Financial Transaction
        if (saved.getPayment() != null && saved.getPayment().getAdvanceAmount() != null
                && saved.getPayment().getAdvanceAmount() != 0) {
            FinancialTransaction txn = new FinancialTransaction();
            txn.setAmount(saved.getPayment().getAdvanceAmount());
            txn.setProfit(0.0);
            txn.setType("CREDIT");
            txn.setCategory("Money Transfer");
            txn.setPaymentMode(
                    saved.getPayment().getPaymentMode() != null ? saved.getPayment().getPaymentMode() : "Cash");
            txn.setDescription(saved.getPayment().getAdvanceAmount() < 0 ? "Revert" : "Money Transfer");
            txn.setRelatedId(saved.getId().toString());
            financialService.recordTransaction(txn);
        }

        return saved;
    }

    public Optional<MoneyTransfer> getTransferById(UUID id) {
        return moneyTransferRepository.findById(id);
    }

    public MoneyTransfer updateStatus(UUID id, String status, Double profit, String profitType, Double finalAmount) {
        MoneyTransfer transfer = moneyTransferRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Transfer not found with id: " + id));

        String oldStatus = transfer.getStatus();

        // Update History
        try {
            java.util.List<java.util.Map<String, Object>> history;
            if (transfer.getStatusHistoryJson() != null && !transfer.getStatusHistoryJson().isEmpty()) {
                history = objectMapper.readValue(transfer.getStatusHistoryJson(),
                        new com.fasterxml.jackson.core.type.TypeReference<java.util.List<java.util.Map<String, Object>>>() {
                        });
            } else {
                history = new java.util.ArrayList<>();
            }

            java.util.Map<String, Object> entry = new java.util.HashMap<>();
            entry.put("status", status);
            entry.put("timestamp", java.time.LocalDateTime.now().toString());
            history.add(entry);
            transfer.setStatusHistoryJson(objectMapper.writeValueAsString(history));
        } catch (Exception e) {
            System.err.println("Error updating status history: " + e.getMessage());
        }

        transfer.setStatus(status);
        MoneyTransfer saved = moneyTransferRepository.save(transfer);

        if ("Done".equalsIgnoreCase(status) && profit != null) {
            FinancialTransaction txn = new FinancialTransaction();
            // User requested storing profit in financial transaction table.
            // We record a DEBIT for the cost and set the profit field.
            Double total = saved.getPayment() != null ? saved.getPayment().getTotalAmount() : 0.0;
            Double amount;
            if (finalAmount != null) {
                amount = finalAmount;
            } else if ("Additional".equalsIgnoreCase(profitType)) {
                amount = total;
            } else {
                amount = total - profit;
            }
            txn.setAmount(amount);
            txn.setProfit(profit);
            txn.setType("DEBIT");
            txn.setCategory("Money Transfer");
            txn.setPaymentMode("Cash");
            txn.setDescription("Money Transfer Completed: " + saved.getRecipientName() + " ("
                    + (saved.getTransferType().equals("UPI") ? saved.getUpiId() : saved.getAccountNumber()) + ")");
            txn.setRelatedId(saved.getId().toString());
            financialService.recordTransaction(txn);
        }

        return saved;
    }

    public MoneyTransfer updateTransfer(UUID id, Map<String, Object> updates) {
        MoneyTransfer transfer = moneyTransferRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Transfer not found"));

        if (updates.containsKey("status")) {
            transfer.setStatus((String) updates.get("status"));
        }
        if (updates.containsKey("upiId"))
            transfer.setUpiId((String) updates.get("upiId"));
        if (updates.containsKey("mobileNumber"))
            transfer.setMobileNumber((String) updates.get("mobileNumber"));
        if (updates.containsKey("recipientName"))
            transfer.setRecipientName((String) updates.get("recipientName"));
        if (updates.containsKey("bankName"))
            transfer.setBankName((String) updates.get("bankName"));
        if (updates.containsKey("ifscCode"))
            transfer.setIfscCode((String) updates.get("ifscCode"));
        if (updates.containsKey("accountNumber"))
            transfer.setAccountNumber((String) updates.get("accountNumber"));
        if (updates.containsKey("amount"))
            transfer.setAmount(((Number) updates.get("amount")).doubleValue());

        // Handle Payment Details updates
        if (updates.containsKey("payment")) {
            Object paymentObj = updates.get("payment");
            if (paymentObj instanceof Map) {
                Map<String, Object> payMap = (Map<String, Object>) paymentObj;
                com.digitalstudio.app.model.Payment payment = transfer.getPayment();
                Double oldAdvance = (payment != null && payment.getAdvanceAmount() != null) ? payment.getAdvanceAmount()
                        : 0.0;

                if (payment == null)
                    payment = new com.digitalstudio.app.model.Payment();

                if (payMap.containsKey("paymentMode"))
                    payment.setPaymentMode((String) payMap.get("paymentMode"));
                if (payMap.containsKey("totalAmount"))
                    payment.setTotalAmount(((Number) payMap.get("totalAmount")).doubleValue());
                if (payMap.containsKey("advanceAmount"))
                    payment.setAdvanceAmount(((Number) payMap.get("advanceAmount")).doubleValue());

                if (payMap.containsKey("discountAmount"))
                    payment.setDiscountAmount(((Number) payMap.get("discountAmount")).doubleValue());
                if (payMap.containsKey("dueAmount"))
                    payment.setDueAmount(((Number) payMap.get("dueAmount")).doubleValue());

                transfer.setPayment(payment);

                Double newAdvance = payment.getAdvanceAmount() != null ? payment.getAdvanceAmount() : 0.0;
                Double paymentDiff = newAdvance - oldAdvance;

                if (paymentDiff != 0) {
                    FinancialTransaction txn = new FinancialTransaction();
                    txn.setAmount(paymentDiff);
                    txn.setProfit(0.0);
                    txn.setType("CREDIT");
                    txn.setCategory("Money Transfer");
                    txn.setPaymentMode(payment.getPaymentMode() != null ? payment.getPaymentMode() : "Cash");
                    txn.setDescription(paymentDiff < 0 ? "Adjust Advance" : "Money Transfer (Updated)");
                    txn.setRelatedId(transfer.getId().toString());
                    financialService.recordTransaction(txn);
                }
            }
        }

        // Handle Customer Updates (Name only usually)
        if (updates.containsKey("customer")) {
            Object custObj = updates.get("customer");
            if (custObj instanceof Map) {
                Map<String, Object> custMap = (Map<String, Object>) custObj;
                Customer cust = transfer.getCustomer();
                if (cust != null && custMap.containsKey("name")) {
                    String newName = (String) custMap.get("name");
                    if (newName != null && !newName.isEmpty() && !newName.equals(cust.getName())) {
                        cust.setName(newName);
                        customerRepository.save(cust);
                    }
                }
            }
        }

        return moneyTransferRepository.save(transfer);
    }

    public List<Map<String, Object>> getSuggestions(String mobile) {
        return moneyTransferRepository.findSuggestions(mobile);
    }
}
