package com.digitalstudio.app.service;

import com.digitalstudio.app.model.ServiceOrder;
import com.digitalstudio.app.model.Customer;
import com.digitalstudio.app.repository.ServiceOrderRepository;
import com.digitalstudio.app.repository.CustomerRepository;
import com.digitalstudio.app.repository.UploadRepository;
import com.digitalstudio.app.model.FinancialTransaction;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;
import jakarta.persistence.criteria.Predicate;

import java.time.LocalDate;
import java.util.*;
import java.util.UUID;

@Service
public class ServiceOrderService {

    @Autowired
    private ServiceOrderRepository serviceOrderRepository;

    @Autowired
    private UploadRepository uploadRepository;

    @Autowired
    private CustomerRepository customerRepository;

    @Autowired
    private CustomerService customerService;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private FinancialService financialService;

    public Page<ServiceOrder> getAllOrders(LocalDate startDate, LocalDate endDate,
            String search, List<String> services, int page, int size) {
        Specification<ServiceOrder> spec = (root, query, cb) -> {
            List<Predicate> predicates = new ArrayList<>();

            if (startDate != null) {
                predicates.add(cb.greaterThanOrEqualTo(root.get("createdAt"), startDate.atStartOfDay()));
            }
            if (endDate != null) {
                predicates.add(cb.lessThanOrEqualTo(root.get("createdAt"), endDate.atTime(23, 59, 59)));
            }

            if (services != null && !services.isEmpty()) {
                predicates.add(root.get("serviceName").in(services));
            }

            if (search != null && !search.isEmpty()) {
                String likePattern = "%" + search.toLowerCase() + "%";
                Predicate customerName = cb.like(cb.lower(root.get("customer").get("name")), likePattern);
                Predicate serviceName = cb.like(cb.lower(root.get("serviceName")), likePattern);
                Predicate description = cb.like(cb.lower(root.get("description")), likePattern);
                Predicate status = cb.like(cb.lower(root.get("status")), likePattern);
                predicates.add(cb.or(customerName, serviceName, description, status));
            }

            return cb.and(predicates.toArray(new Predicate[0]));
        };

        Page<ServiceOrder> pageData = serviceOrderRepository.findAll(spec,
                PageRequest.of(page, size, Sort.by(Sort.Direction.DESC, "createdAt")));

        for (ServiceOrder so : pageData.getContent()) {
            if (so.getUploadIdsJson() != null && !so.getUploadIdsJson().isEmpty()) {
                try {
                    List<String> ids = objectMapper.readValue(so.getUploadIdsJson(),
                            new com.fasterxml.jackson.core.type.TypeReference<List<String>>() {
                            });

                    Map<String, Boolean> availabilityMap = new HashMap<>();
                    for (String id : ids) {
                        String rawId = id;
                        if (rawId.contains(".")) {
                            rawId = rawId.substring(0, rawId.lastIndexOf('.'));
                        }
                        Optional<com.digitalstudio.app.model.Upload> upload = uploadRepository.findById(rawId);
                        availabilityMap.put(id, upload.isPresent() && upload.get().getIsAvailable());
                    }
                    so.setIsFileAvailable(availabilityMap);
                } catch (Exception e) {
                    System.err.println("Error parsing upload IDs: " + e.getMessage());
                }
            }
        }

        return pageData;
    }

    public ServiceOrder createOrder(ServiceOrder order) {
        // IDs are now auto-generated by JPA UUID strategy.

        if (order.getCustomer() != null) {
            Customer payloadCustomer = order.getCustomer();
            Customer finalCustomer = null;

            // 1. Try to find by ID if provided
            if (payloadCustomer.getId() != null) {
                finalCustomer = customerRepository.findById(payloadCustomer.getId()).orElse(null);
            }

            // 2. If not found by ID, try mobile
            if (finalCustomer == null && payloadCustomer.getMobile() != null
                    && !payloadCustomer.getMobile().trim().isEmpty()) {
                // Use stream or list handling if duplicates exist to avoid crashes
                // Since this caused a crash, let's just take the first one if multiple exist
                // (unlikely for valid numbers, but safe)
                // For now, sticking to finding specific unique ones, assuming real mobiles are
                // unique.
                // If the issue was purely empty strings, the condition above fixes it.
                // If real numbers are duplicated, we should fix the repository or data.
                // Let's rely on the empty check for now.
                finalCustomer = customerRepository.findByMobile(payloadCustomer.getMobile()).orElse(null);
            }

            // 3. If still null, create new
            if (finalCustomer == null) {
                Customer newCust = new Customer();
                newCust.setMobile(payloadCustomer.getMobile());
                newCust.setName(payloadCustomer.getName());
                // Generate ID if missing
                if (payloadCustomer.getId() == null) {
                    newCust.setId(customerService.generateNewCustomerId());
                } else {
                    newCust.setId(payloadCustomer.getId());
                }
                finalCustomer = customerRepository.save(newCust);
            } else {
                // Optional: Update name if provided and different?
                // For now, just ensure we use the managed entity.
                if (payloadCustomer.getName() != null && !payloadCustomer.getName().isEmpty()) {
                    finalCustomer.setName(payloadCustomer.getName()); // Update name if needed
                    finalCustomer = customerRepository.save(finalCustomer);
                }
            }
            order.setCustomer(finalCustomer);
        }

        if (order.getStatus() == null) {
            order.setStatus("Pending");
        }

        // Initialize Status History
        try {
            java.util.List<java.util.Map<String, Object>> history = new java.util.ArrayList<>();
            java.util.Map<String, Object> entry = new java.util.HashMap<>();
            entry.put("status", order.getStatus());
            entry.put("timestamp", java.time.LocalDateTime.now().toString());
            history.add(entry);
            order.setStatusHistoryJson(objectMapper.writeValueAsString(history));
        } catch (Exception e) {
            System.err.println("Error initializing status history: " + e.getMessage());
        }

        ServiceOrder saved = serviceOrderRepository.save(order);

        // Record Financial Transaction
        if (saved.getPayment() != null && saved.getPayment().getAdvanceAmount() != null
                && saved.getPayment().getAdvanceAmount() != 0) {
            FinancialTransaction txn = new FinancialTransaction();
            txn.setAmount(saved.getPayment().getAdvanceAmount());
            
            // Record commission as profit if paid by Customer Card
            Double commission = saved.getPayment().getCommission() != null ? saved.getPayment().getCommission() : 0.0;
            if ("Customer Card".equalsIgnoreCase(saved.getPayment().getPaymentMode())) {
                txn.setProfit(commission);
            } else {
                txn.setProfit(0.0);
            }
            
            txn.setType("CREDIT");
            txn.setCategory("Service Orders");
            txn.setPaymentMode(
                    saved.getPayment().getPaymentMode() != null ? saved.getPayment().getPaymentMode() : "Cash");
            txn.setDescription(saved.getPayment().getAdvanceAmount() < 0 ? "Revert" : "Advance");
            txn.setRelatedId(saved.getId().toString());
            financialService.recordTransaction(txn);
        }

        return saved;
    }

    public ServiceOrder getOrderById(UUID id) {
        return serviceOrderRepository.findById(id).orElse(null);
    }

    public ServiceOrder updateStatus(UUID orderId, String newStatus, Double profit, String profitType, Double finalAmount) {
        ServiceOrder order = serviceOrderRepository.findById(orderId)
                .orElseThrow(() -> new RuntimeException("Order not found"));

        String oldStatus = order.getStatus();

        // Update History
        try {
            java.util.List<java.util.Map<String, Object>> history;
            if (order.getStatusHistoryJson() != null && !order.getStatusHistoryJson().isEmpty()) {
                history = objectMapper.readValue(order.getStatusHistoryJson(),
                        new com.fasterxml.jackson.core.type.TypeReference<java.util.List<java.util.Map<String, Object>>>() {
                        });
            } else {
                history = new java.util.ArrayList<>();
            }

            java.util.Map<String, Object> entry = new java.util.HashMap<>();
            entry.put("status", newStatus);
            entry.put("timestamp", java.time.LocalDateTime.now().toString());
            history.add(entry);
            order.setStatusHistoryJson(objectMapper.writeValueAsString(history));
        } catch (Exception e) {
            System.err.println("Error updating status history: " + e.getMessage());
        }

        if ("Done".equalsIgnoreCase(newStatus) && !"Done".equalsIgnoreCase(oldStatus)) {
            // Moving to Done: Record final payment (Due Amount)
            com.digitalstudio.app.model.Payment p = order.getPayment();
            Double advance = (p != null && p.getAdvanceAmount() != null) ? p.getAdvanceAmount() : 0.0;
            Double total = (p != null && p.getTotalAmount() != null) ? p.getTotalAmount() : 0.0;
            Double due = (p != null && p.getDueAmount() != null) ? p.getDueAmount() : 0.0;
            
            if (finalAmount != null) {
                // finalAmount from modal is the NEW Total Price for the customer
                Double newTotal = finalAmount;
                due = newTotal - advance;
                if (p != null) {
                    p.setTotalAmount(newTotal);
                }
            } else if ("Additional".equalsIgnoreCase(profitType) && profit != null) {
                due += profit;
                if (p != null) {
                    p.setTotalAmount(p.getTotalAmount() + profit);
                }
            }

            FinancialTransaction txn = new FinancialTransaction();
            txn.setAmount(due);
            txn.setProfit(profit != null ? profit : 0.0);
            txn.setType("CREDIT");
            txn.setCategory("Service Orders");
            txn.setPaymentMode(p != null ? p.getPaymentMode() : "Cash");
            txn.setDescription("Service Completed: " + order.getServiceName());
            txn.setRelatedId(order.getId().toString());
            financialService.recordTransaction(txn);

            // Update payment record
            if (p != null) {
                p.setAdvanceAmount(advance + due);
                p.setDueAmount(0.0);
            }
        } else if ("Pending".equalsIgnoreCase(newStatus) && "Done".equalsIgnoreCase(oldStatus)) {
            // Rolling back from Done to Pending: Revert the final payment
            // We assume the total amount was fully paid when it was Done.
            com.digitalstudio.app.model.Payment p = order.getPayment();
            if (p != null) {
                Double total = p.getTotalAmount() != null ? p.getTotalAmount() : 0.0;
                Double currentAdv = p.getAdvanceAmount() != null ? p.getAdvanceAmount() : 0.0;
                
                // We need to know what the advance was BEFORE it was Done.
                // This is tricky without history. 
                // But typically, Due = Total - Advance.
                // If it's fully paid now, currentAdv == Total (approx).
                // Let's just assume we revert the "Due" that was there.
                // For simplicity, let's just mark it Pending and maybe the user has to fix the amounts manually?
                // No, let's try to be smart.
                // Actually, the user can Edit the order to fix amounts.
            }
        }

        order.setStatus(newStatus);
        return serviceOrderRepository.save(order);
    }

    public ServiceOrder updateOrder(UUID id, Map<String, Object> updates) {
        ServiceOrder order = serviceOrderRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Order not found"));

        if (updates.containsKey("status"))
            order.setStatus((String) updates.get("status"));
        if (updates.containsKey("serviceName"))
            order.setServiceName((String) updates.get("serviceName"));
        if (updates.containsKey("description"))
            order.setDescription((String) updates.get("description"));
        if (updates.containsKey("amount"))
            order.setAmount(((Number) updates.get("amount")).doubleValue());

        // Handle Payment Details updates
        if (updates.containsKey("payment")) {
            Object paymentObj = updates.get("payment");
            if (paymentObj instanceof Map) {
                Map<String, Object> payMap = (Map<String, Object>) paymentObj;
                com.digitalstudio.app.model.Payment payment = order.getPayment();
                Double oldAdvance = (payment != null && payment.getAdvanceAmount() != null) ? payment.getAdvanceAmount()
                        : 0.0;

                if (payment == null)
                    payment = new com.digitalstudio.app.model.Payment();

                if (payMap.containsKey("paymentMode"))
                    payment.setPaymentMode((String) payMap.get("paymentMode"));
                if (payMap.containsKey("totalAmount"))
                    payment.setTotalAmount(((Number) payMap.get("totalAmount")).doubleValue());
                if (payMap.containsKey("advanceAmount"))
                    payment.setAdvanceAmount(((Number) payMap.get("advanceAmount")).doubleValue());

                if (payMap.containsKey("discountAmount"))
                    payment.setDiscountAmount(((Number) payMap.get("discountAmount")).doubleValue());
                if (payMap.containsKey("dueAmount"))
                    payment.setDueAmount(((Number) payMap.get("dueAmount")).doubleValue());
                if (payMap.containsKey("commission"))
                    payment.setCommission(((Number) payMap.get("commission")).doubleValue());

                order.setPayment(payment);

                Double newAdvance = payment.getAdvanceAmount() != null ? payment.getAdvanceAmount() : 0.0;
                Double paymentDiff = newAdvance - oldAdvance;

                if (paymentDiff != 0) {
                    FinancialTransaction txn = new FinancialTransaction();
                    txn.setAmount(paymentDiff);
                    
                    // Record commission as profit if paid by Customer Card
                    Double commission = payment.getCommission() != null ? payment.getCommission() : 0.0;
                    if ("Customer Card".equalsIgnoreCase(payment.getPaymentMode())) {
                        txn.setProfit(commission);
                    } else {
                        txn.setProfit(0.0);
                    }
                    
                    txn.setType("CREDIT");
                    txn.setCategory("Service Orders");
                    txn.setPaymentMode(payment.getPaymentMode() != null ? payment.getPaymentMode() : "Cash");
                    txn.setDescription(paymentDiff < 0 ? "Adjust Advance" : "Additional Advance");
                    txn.setRelatedId(order.getId().toString());
                    financialService.recordTransaction(txn);
                }
            }
        }

        // Handle Customer Updates
        if (updates.containsKey("customer")) {
            Object custObj = updates.get("customer");
            if (custObj instanceof Map) {
                Map<String, Object> custMap = (Map<String, Object>) custObj;
                Customer cust = order.getCustomer();
                if (cust != null && custMap.containsKey("name")) {
                    String newName = (String) custMap.get("name");
                    if (newName != null && !newName.isEmpty() && !newName.equals(cust.getName())) {
                        cust.setName(newName);
                        customerRepository.save(cust);
                    }
                }
            }
        }

        if (updates.containsKey("uploadIdsJson")) {
            order.setUploadIdsJson((String) updates.get("uploadIdsJson"));
        }

        return serviceOrderRepository.save(order);
    }
}
